# Generated by Django 5.2.7 on 2025-10-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_bookingdate_booking_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='description',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='inventory',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
